-- Tablas

-- Datos generales / Personas
-- { Campos: ID, NOMBRE, DNI, TEL, EMAIL, DIRECCIÓN, FECHA NACIMIENTO, SEXO, CATEGORIA, ESTADO }
-- -- -- -- Membresias
-- -- -- -- Estados Civiles
-- -- -- -- País
-- -- -- -- Departamentos (18)
-- -- -- -- Ciudades (3 * cada depto)
-- -- -- -- Sexo
-- -- -- -- Categoria (Empleado - Cliente)
-- -- -- -- Membresía
-- Inventario
-- { Campos: ID, TITULO, ANIO, GENERO, DURACION, FORMATO, ESTADO, DESCRIP, IDIOMA, CANTIDAD, PRECIO, CLASIFICACION }
-- -- -- -- Genero
-- -- -- -- Tipo de Transacción
-- -- -- -- Formato
-- -- -- -- Estado
-- -- -- -- Clasificacion
-- -- -- -- Idioma
-- -- -- -- Director
-- Factura
-- { Campos: ID, MEOTODO PAGO, CLIENTE, #FACTURA, FECHA FACT, TIPO DE TRANSACCION, IMPUESTO, DESCUENTO, SUBTOTAL, ID_PELI, FECHA_DEVOLUCION, TOTAL }
-- -- -- -- Método de Pago
-- -- -- -- Transacción
-- Usuarios
-- Roles