--- VISTA PARA LISTAR CLIENTES
---- LA VISTA TIENE QUE TRAER EL NOMBRE COMPLETO, DNI, 
-- VISTA PARA LISTAR EMPLEADOS

-- PROCEDIMIENTO PARA INSERTAR CLIENTES

-- PROCEDIMIENTO PARA INSERTAR EMPLEADOS